name: eli-africa
favicon: null
layout_spectrum: 0.2745163661893457
typography_spectrum: 0.5042839362286031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.10799769801087677
  lightness: 0.134439637651667
  saturation: 0.8013785262592137
  rhythmicContrast: 0.8524400177411735
purpose: []
