name: eli-africa
favicon: null
layout_spectrum: 0.2745163661893457
typography_spectrum: 0.5042839362286031
title: ELI Africa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#93a692'
    - '#272a2f'
    - '#6d7160'
    - '#d84d3a'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
